### PR TITLE
Update gemspec

### PR DESCRIPTION
**Pull request by rangeroob**

### CODE REVIEW

**Comment by pboling** [comment]
Is this going to remain as a separate branch?

**Comment by rangeroob** [comment]
@pboling hey if its useful for you I'll try and clean it up either this branch or create a new one that is cleaner commit wise and merge it in.

**Comment by rangeroob** [comment]
branches 1-4-2 and master should have the updated gemspec files needed. So you should be able to build from either and with the sqlite3.gemspec it should be able to used in place of sqlite3 within Ruby on Rails without conflicting with the standard gem.

Aside I noticed I did not have issues enabled on this fork if you have any other questions please open an issue.

Thanks

**Comment by pboling** [comment]
Thanks @rangeroob !

**Pull request closed without merging**
